#ifndef H_CANVAS_CONFIG_H
#define H_CANVAS_CONFIG_H

#cmakedefine CANVAS_SHARED

#define CANVAS_VERSION_MAJOR ${CANVAS_VERSION_MAJOR}
#define CANVAS_VERSION_MINOR ${CANVAS_VERSION_MINOR}
#define CANVAS_VERSION_PATCH ${CANVAS_VERSION_PATCH}
#define CANVAS_VERSION_BUILD "${CANVAS_VERSION_BUILD}"

#endif